"SMS-2001.txt":
  :pattern: '^(\"(.*)\" <)?([0-9]+)>?\n(.+)\n(.*)\n\n'
  :fields:
    sender_name: $1
    sender_nr: $2
    date: $3
    text: $4
    #source

"SMS-2002-2003.txt":
  :pattern: '^(\"(.*)\" <)?([0-9]+)>?\n(.+)\n(.*)\n\n'
  :fields:
    sender_name: $1
    sender_nr: $2
    date: $3
    text: $4
    #source
      #  :date_pattern: